### ISSUE TITLE
Model and Form ImageFields should support image shrinking

### ISSUE THREAD

**Issue by Coalpaw** [uploadcare/pyuploadcare#150]
Since the upload widget can normally be configured to shrink an image via the "data-image-shrink" attribute, it would be helpful to be able to configure a field to set this automatically rather than having to resort to custom admin code to inject it into the widget everywhere it is required.

**Comment by dmitry-mukhin** [comment]
Not sure I follow.
We're talking about Django admin? You can add any extra attributes to the widget via model definition so no "custom code" is required.

@Coalpaw please elaborate.

**Comment by Coalpaw** [comment]
@dmitry-mukhin You can't really do it via a model field definition (unless you know something I don't).  Attributes can only be added via the widget, which I agree can be done by overriding the widget in the admin and adding the required attribs, or by tacking on the attrib to the widget during the admin init which is also a common method.  However, you are already adding a custom kwarg to the ImageField (manual_crop) which automagically adds the "data-crop" attrib to the underlying custom widget.  Presumably this is due to the validation of the crop string, otherwise why not leave this up to the user to implement as a widget override as well?

**Comment by dmitry-mukhin** [comment]
I was referring to this:
https://github.com/uploadcare/pyuploadcare/blob/master/docs/django-widget.rst#advanced-widget-options

```python
class CandidateForm(forms.Form):
    photo = ImageField(widget=FileWidget(attrs={
        'data-cdn-base': 'https://cdn.super-candidates.com',
        'data-image-shrink': '1024x1024',
    }))
```

**Comment by Coalpaw** [comment]
I see.  That would normally be how I would do it.  I guess it is a little confusing as to why there would be the "manual_crop" kwarg on the field to set a widget attrib but other uploadcare-specific attributes can't be set that way and you have to fall back to manually specifying the widget and its configuration.

**Comment by dmitry-mukhin** [comment]
Widget options are [numerous](https://uploadcare.com/docs/file_uploads/widget/options/) and are being added much faster than this Django integration lib can be updated.
Also, Django lib isn't strictly connected to a particular version of the widget so some things we might add here could be absent in an older version of the widget one can choose to use for some reason.

That's why we've tried to add "native" support for some of the most used settings and give a way to set anything else that can be added in the future via widget's settings.

Let me know if you're happy and I can close the issue.

**Comment by Coalpaw** [comment]
Sounds good, closing the issue.
