### ISSUE TITLE
Badges in readme should link to appropriate pages, not images)

### ISSUE THREAD

**Issue by dmitry-mukhin** [uploadcare/pyuploadcare#236]
E.g. to https://pypi.org/project/pyuploadcare/

**Comment by evgkirov** [comment]
Not sure where the "tech stack" should lead to.

**Comment by rsedykh** [comment]
I assume back in the days it was https://stackshare.io/uploadcare, but I doubt we need this these days.

**Comment by evgkirov** [comment]
Similar thing with Coveralls.

Here's the page: https://coveralls.io/github/uploadcare/pyuploadcare

It seems it stopped working since the switch from Travis CI to GitHub Actions — or even before that — 4 years ago.

I can either remove this badge or create an issue on that topic.

<img width="1147" alt="Screenshot 2023-06-26 at 21 36 53" src="https://github.com/uploadcare/pyuploadcare/assets/208751/b874930a-c686-4b62-a437-017fefd062ad">

**Comment by rsedykh** [comment]
Let's remove old stuff.

**Comment by dmitry-mukhin** [comment]
1. coverage test, ideally we need to run those and show results. let's have a separate task for this.
2. stackshare link is still relevant, can we bring this back?

@rsedykh

**Comment by evgkirov** [comment]
#247 a separate task for coverage
