### ISSUE TITLE
RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.

### ISSUE THREAD

**Issue by avsd** [uploadcare/pyuploadcare#94]
```
django/db/models/fields/subclassing.py:22: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  RemovedInDjango110Warning
```

See `FileField` and `FileGroupField` classes: https://github.com/uploadcare/pyuploadcare/blob/master/pyuploadcare/dj/models.py#L14

**Comment by zerc** [comment]
### It was

The pivotal purpose of `SubfieldBase` is to wrap the method `Field.contribute_to_class` for setting a descriptor for working with a field's data. This descriptor  uses the `Field.to_python` for every assignment of value to the field.  For more details [look at source](https://github.com/django/django/blob/1.9.1/django/db/models/fields/subclassing.py#L43-L44).

In other words, currently we have a next logic:

```python
>>> from gallery.models import *
>>> photo = Photo()
>>> photo.arbitrary_file = '3addab78-6368-4c55-ac08-22412b6a2a4c'
>>> photo.arbitrary_file
<uploadcare.File 3addab78-6368-4c55-ac08-22412b6a2a4c>
```

### It will

Starts with the Django1.8 the `SubfieldBase` is deprecated. Instead of using it, we need to define our own `Field.from_db_value` which called **after** the data come from a database. And because we don't have a descriptor, the code above works differently:

```python
>>> from gallery.models import *
>>> photo = Photo()
>>> photo.arbitrary_file = '3addab78-6368-4c55-ac08-22412b6a2a4c'
>>> photo.arbitrary_file
'3addab78-6368-4c55-ac08-22412b6a2a4c'
```

As I said, transformation now happens only when data comes from a database:

```python
>>> from gallery.models import *
>>> Photo.objects.all()[0].arbitrary_file
<uploadcare.File c915ecda-4fe7-4e69-b3be-b8850173b541>
```

### Summary

I see three variants here:

**Support both variants depending on version of Django**
Very hard to support.

**Use the new behavior including for old versions of Django**
It breaks backward compatibility. We need to release a major version of `pyuploadcare`.

**Use current behavior**
Move deprecated part from Django to `pyuploadcare`.

I think the 3rd way is actual right now. Because it easy to implement, support and I really not sure what the new behavior is a good fit us.

**Comment by homm** [comment]
+1 for Move deprecated part from Django to pyuploadcare.

**Comment by zerc** [comment]
Ok, I [delivered this](https://github.com/uploadcare/pyuploadcare/blob/master/pyuploadcare/dj/subclassing.py).

**Comment by mozinator** [comment]
@zerc Thank you for fixing this

**Comment by zerc** [comment]
@mozinator You welcome :)
